### ISSUE TITLE
[META] Cache issues & improvements

### ISSUE THREAD

**Issue by pepibumur** [tuist/tuist#1975]
This is an issue to keep track of all the cache-related issues.
- [x] When the `autosynthesizing` interfaces for resources feature is enabled, the `tuist cache print-hashes` command fails to run because it tries to hash non-existing files (those are generated when the side effects are executed).
- [ ] The current implementation doesn't support the caching of transitive bundles. We should extend the logic to have support for caching them, and doing the right mutations in the graph when users run the `tuist focus` command.
- [x] `tuist cache warm` fails with file not found when a targetAction.outputPaths or targetAction.outputFileListPaths use environment variables [issue](https://github.com/tuist/tuist/issues/1870) [PR](https://github.com/tuist/tuist/pull/2018)
- [X]  App extensions are failing to build for "linking a dylib which is not safe for use in application extension" which was only a warning without using cache - @andreacipriani  tried on a sample project and couldn't reproduce. You get the expected warning but `tuist cache warm` works as expected
- [x] @RomainBoulay reported that using `latest` as the simulator when warming up the cache might not work if developers have custom simulators in their environment. [PR](https://github.com/tuist/tuist/pull/2016)
- [ ] @RomainBoulay reported that using `tuist focus` may lead to an incorrect project generation when some of the dependent targets are present in the local cache.
- [ ] Address un-needed(?)(TBC) warning: ```Target "XXX" has been linked against ["A", "B"], it is a static product so may introduce unwanted side effects.```
- [x] Missing required module 'XXX' when running unit tests with cached dependencies [issue](https://github.com/tuist/tuist/issues/2023)
- [ ] When developers change the default derived data to be relative to the project's directory, the cache warming fails to resolve the path of the output directory.

## Ideas
- [ ] Debugging why branches of the dependency graph are not cacheable is tricky. I think we can build a `tuist cache graph` that highlights what targets are cacheable and which ones are not.

**Comment by pepibumur** [comment]
I started working on hashing the source files generated by the mapper that synthesizes interfaces from resources. Debugging caching with @RomainBoulay showed that commands like `print-hashes` that don't generate the project, fail because files that are generated through side effects don't exist unless you generate the project.

**Comment by mollyIV** [comment]
Hey Pedro 👋 

I was wondering, if we could link the following issues in the issue's description: 

* https://github.com/tuist/tuist/issues/2190
* https://github.com/tuist/tuist/issues/2191
