### ISSUE TITLE
tuist project generator library

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#205]
Based on the [original proposal #192](https://github.com/tuist/tuist/issues/192) this issue is for tracking progress on creating a new project generator library.

**Describe the solution you'd like**
A new library `TuistGenerator` will be created that will host all the Xcode project generation related code to allow re-usablity within other Swift packages. 

Dependencies:

- [x] #192: Finalize proposal
- [x] #197: Add integration tests for the generate command
- [x] #203: Extract "Up" command metadata from the graph and the manifest file

Steps:

- [x] #224: Create `TuistGenerator` library module 
- [x] #237: Decouple the model and generator classes from `ProjectDescription`
- [x] #242: Introduce `Generator` component temporarily to `TuistKit` to ease migration to `TuistGenerator`
- [x] #257: Add ability to customize project structure (at the generator level)
   - (This unlocks the next item to allow creating the manifest target without needing dedicated logic)
- [x] #271: Unify manifest target and configuration generation
- [x] #262: Add ability to specify the inclusion of workspace files (at the generator level)
  - This will allow us to add manifest files to the workspace without requiring the manifest loader within the generator itself
- [ ] #276: Decouple embed frameworks phase from tuist 
- [ ] Move existing models and generator classes (defined below) with minimal modifications

Details:

- Migrate the following classes from `TuistKit` to a new module `TuistGenerator`

```
├── Extensions
│   ├── AbsolutePath+Extras.swift
│   └── Optional+Extras.swift
├── Generator
│   ├── BuildPhaseGenerator.swift
│   ├── ConfigGenerator.swift
│   ├── FileGenerator.swift
│   ├── GeneratedProject.swift
│   ├── GenerationDirectory.swift
│   ├── GenerationOptions.swift
│   ├── LinkGenerator.swift
│   ├── ProjectDirectoryHelper.swift
│   ├── ProjectFileElements.swift
│   ├── ProjectGenerator.swift
│   ├── ProjectGroups.swift
│   ├── SchemesGenerator.swift
│   ├── TargetGenerator.swift
│   └── WorkspaceGenerator.swift
├── Graph
│   ├── Graph.swift
│   ├── GraphCircularDetector.swift
│   ├── GraphLoader.swift
│   ├── GraphLoaderCache.swift
│   ├── GraphLoadingError.swift
│   └── GraphNode.swift
├── Linter
│   ├── GraphLinter.swift
│   ├── LintingIssue.swift
│   ├── ProjectLinter.swift
│   ├── SettingsLinter.swift
│   ├── TargetActionLinter.swift
│   └── TargetLinter.swift
├── Model
│   ├── BuildConfiguration.swift
│   ├── CoreDataModel.swift
│   ├── Dependency.swift
│   ├── Headers.swift
│   ├── Platform.swift
│   ├── Playgrounds.swift
│   ├── Product.swift
│   ├── Project.swift
│   ├── Settings.swift
│   ├── Target.swift
│   ├── TargetAction.swift
│   ├── Workspace.swift
│   └── XcodeRepresentable.swift
└── Utils
    └── ResourceLocator.swift
```

- The entry point:

```swift
public class TuistGenerator {

    private let graphLoader: GraphLoading
    private let modelLoader: ModelLoading
    private let workspaceGenerator: WorkspaceGenerating

    /// Generates a project at a given path and returns the path the `.xcworkspace` file
    public func generateProject(basePath: AbsolutePath) throws -> AbsolutePath {
      // ...
   }
   
    /// Generates a workspace at a given path and returns the path the `.xcworkspace` file
   public func generateWorkspace(basePath: AbsolutePath) throws -> AbsolutePath {
      // ...
   }
}
```

- The key part is the `ModelLoading` protocol that will be implemented by clients of the library:

```swift
public protocol ModelLoading {
    func loadProject(at path: AbsolutePath) throws -> Project
    func loadWorkspace(at path: AbsolutePath) throws -> Workspace
}
```

- Related unit tests will also be migrated from `TuistKitTests` to ensure the library is well covered

**Describe alternatives you've considered**
 The [original proposal #192](https://github.com/tuist/tuist/issues/192) covers the alternatives considered.

Additional feedback is welcome

**Comment by kwridan** [comment]
@pepibumur, @ollieatkinson - we finally have a [branch](https://github.com/bloomberg/tuist/tree/feature/205-tuist-generator-library) for the proposed library changes. 

It's quite large so we'd like to chunk it up to ease it's review. However it might be useful to see the changes all together ahead of submitting any PRs in case there are any design flaws that require addressing.

Afterwards, we were thinking of chunking it up as follows: 
- Create `TuistGenerator` library module & move existing models and generator classes (defined above) with minimal modifications
 - Decouple the model and generator classes from `ProjectDescription`

Keen to hear your thoughts and feedback!

**Comment by pepibumur** [comment]
Sorry that I haven't been that responsive lately with the open source stuff.

Wow, that's an impressive work. I think chunking it up is a good idea.

I skimmed through the code *(I might have missed something)* and it looks good in terms of structure and code style. I couldn't find anything that is not conventional so I'd say go ahead with opening the PRs.

**Comment by ollieatkinson** [comment]
> It's quite large so we'd like to chunk it up to ease it's review.

I would definitely break it down as it's quite difficult to consume all of it in one review (at least well enough to feedback)

I didn't notice any high-level gotchas when reviewing - I would agree with @pepibumur that it's ready to start submitting for review in P/R's! Nice work!
