### ISSUE TITLE
Support resources for static libraries & frameworks

### ISSUE THREAD

**Issue by kwridan** [tuist/tuist#290]
**Status**

- [x] #321: Add `.bundle` product types to `TuistGenerator`
- [x] #348: Support transitively depending on `.bundle` targets 
- [x] #374: Ensure bundle targets in other projects are built in the correct order
- [x] #479: Expose `.bundle` products in the project manifest (to allow manually handling / dealing with resource bundles)
- [ ] Support generating a `ResourceBundle.swift` for bundle targets that is added to targets that depend on it
- [ ] Support implicit creation of resource bundle targets when static frameworks include resources 

---
**Overview**

Currently resources are only supported in (dynamic) frameworks and top level targets such as applications and test targets.

Often times when a target that doesn't support resources such as static libraries or frameworks requires them, a few solutions are resorted to:

1) Create a resource bundle 

- This is a target dedicated to hosting resources
- Must be included in the resources of the top level target
- Additional code is needed to find the appropriate `Bundle` to load those resources from

2) Copy the resources directly to the top level product that supports them (e.g. application)

- All required resources are manually copied / included into the top level target
- The code to access resources is the same as the one used to access resources within the top level target (e.g. `Bundle.main`)

Both issues have their pros and cons:

1) Is more modular and avoids resource name clashes, however requires additional setup that is error prone when scaling up to several projects
2) Is simpler for small projects however doesn't scale very well when more projects are added

Some example use cases for this are:

- Having shared UI components defined in static libraries or frameworks that require assets / fonts or even `xib` files to drive their layout.

**Describe the solution you'd like**

There is an opportunity for Tuist to help manage some of this work. It can expand on option 1) where it can auto create resource bundles and link them appropriately (_rules / convention to be determined_).

This approach is inspired by the draft Swift PM proposal for the same topic.

**Incremental Solution**

Perhaps initially as a step to explore this space and source more use cases, Tuist could support this in a slightly more manual fashion where it would allow defining bundle targets.

```swift
let project = Project(name: "MyProject", targets: [
    Target(name: "MyApp",
           platform: .iOS,
           product: .app,
           bundleId: "com.myapp.targets.myapp",
           infoPlist: "SupportingFiles/MyApp-Info.plist",
           sources: ["Sources/**"],
           dependencies: [
            .target(name: "MyLibrary"),
            .target(name: "MyResources"),
        ]),
    Target(name: "MyLibrary",
           platform: .iOS,
           product: .staticFramework,
           bundleId: "com.myapp.targets.mylibrary",
           infoPlist: "SupportingFiles/MyLibrary-Info.plist",
           sources: ["Sources/**"]),
    Target(name: "MyResources",
           platform: .iOS, 
           product: .bundle,
           bundleId: "com.myapp.targets.myresources",
           infoPlist: "SupportingFiles/MyResources-Info.plist",
           resources: ["Resources/**/*.png", "Sources/**/*.xib"])
    ])
```

This would result in `MyResources` to be copied to `MyApp`'s resources

A follow up to that could be managing this transitively to allow this to happen more implicitly:

```swift
let project = Project(name: "MyProject", targets: [
    Target(name: "MyApp",
           platform: .iOS,
           product: .app,
           bundleId: "com.myapp.targets.myapp",
           infoPlist: "SupportingFiles/MyApp-Info.plist",
           sources: ["Sources/**"],
           dependencies: [
            .target(name: "MyLibrary"),
        ]),
    Target(name: "MyLibrary",
           platform: .iOS,
           product: .staticFramework,
           bundleId: "com.myapp.targets.mylibrary",
           infoPlist: "SupportingFiles/MyLibrary-Info.plist",
           sources: ["Sources/**"],
           dependencies: [
            .target(name: "MyResources"),
        ]),
    Target(name: "MyResources",
           platform: .iOS, 
           product: .bundle,
           bundleId: "com.myapp.targets.myresources",
           infoPlist: "SupportingFiles/MyResources-Info.plist",
           resources: ["Resources/**/*.png", "Sources/**/*.xib"])
    ])
```

**References**

- [[DRAFT] Package manager resources](https://github.com/abertelrud/swift-evolution/blob/package-manager-resources/proposals/NNNN-package-manager-resources.md)

**Comment by pepibumur** [comment]
I'd add as a con of copying resources into the main bundle that the names can collide. Talking to a friend he told me that they had a few issues with this.

**Comment by pepibumur** [comment]
Thanks for the write-up @kwridan. I think the proposal that you suggested is utterly valid and an option we can go for. I'm a bit biased towards defining the resources as part of the targets because of the following reasons:
- Most developers are slightly familiar with frameworks and libraries but have barely configured their projects to include resources in bundles. I think we'd be presenting them with a new setup that they  may not familiar with even in Xcode.
- The attributes from the bundled can be inferred from the target the resources are associated to so having attributes like `platform`, `bundleId`, `infoPlist`, feels redundant.

This is how I see the manifest:

```swift
let project = Project(name: "MyProject", targets: [
    Target(name: "MyApp",
           platform: .iOS,
           product: .app,
           bundleId: "com.myapp.targets.myapp",
           infoPlist: "SupportingFiles/MyApp-Info.plist",
           sources: ["Sources/**"],
           dependencies: [
            .target(name: "MyLibrary"),
        ]),
    Target(name: "MyLibrary",
           platform: .iOS,
           product: .staticFramework,
           bundleId: "com.myapp.targets.mylibrary",
           infoPlist: "SupportingFiles/MyLibrary-Info.plist",
           sources: ["Sources/**"],
           resources: ["Resources/**/*.png", "Sources/**/*.xib"]),
           dependencies: [
            .target(name: "MyResources"),
        ]),
```
Depending on the associated target, we'd:
- Libraries: Create a bundle that we'd copy into the product.
- Frameworks/apps: Copy the resources into the bundle.

In both cases, I'd generate an extension as you suggested that abstracts the implementation detail of where the resources are located. Something along the lines of:

```swift
extension Bundle {
  static var myTarget: Bundle {
    if isLibrary {
     // Return the bundle inside the main bundle
   } else {
    // Return the bundle
    }
  }
}

**Comment by kwridan** [comment]
Just discovered that simply having a resource bundle in the "Copy Bundle Resources" phase of a target doesn't get Xcode to build it.

This is less of an issue when the resource bundle is being copied to a target within the same project as it can be added an explicit target dependency.

 For targets in other projects there are a few options:

- Add the resource bundle target to the scheme as one of the buildable targets 
  - Not too excited about this option as it means we would rely on a specific scheme setting for the entire workspace to be complete / correct
- Employ a similar workaround to the one currently used for static targets - Add a copy files phase from products directory to products directory for the resource bundle product within the target that needs to copy it
  - It looks strange, but this technique is already employed for static products so at least it's consistent 🙂
