### ISSUE TITLE
Replace RxSwift to async/await

### ISSUE THREAD

**Issue by adellibovi** [tuist/tuist#4004]
Now that we already have setup release build to support Swift concurrency, we would like to move forward to drop RxSwift (and probably Combine) in favour of async/await.

I will try to list a list of tasks to do, so we can keep track and assign to different people. If you are interested in one, just mention which task you want to work on in a comment.

Tasks:

- [x] Update RxSwift #4003
- [x] Support `@main` async #4003
- [x] Remove RxSwift from `Cache`, `CacheStoring`, `CacheRemoteStorage`, `CacheLocalStorage`, `CacheGraphMutator` etc... #4003 
- [x] `TuistAnalyticsBackboneBackend`, `TuistAnalyticsBackend`, `TuistAnalyticsCloudBackend`, `TuistAnalyticsDispatcher`, `URLSessionScheduler` #4005
- [x] `CacheBundleBuilder`, `CacheFrameworkBuilder`, `CacheXCFrameworkBuilder` #4014
- [x] `SimulatorController` #4013
- [x]  `ManifestLoader` #4011
- [x] `AsyncQueue`, `AsyncQueuePersistor` #4026
- [x] `XcodeBuildController`, `XcodeBuildControlling`, `Observable+XcodeBuildOutput` #4029
- [x] `Observable+System`, `System`, `SystemEvent` #4029
- [x] Merge it in 3.0 branch and remove any leftover there, too

**Comment by adellibovi** [comment]
I will take the next one `TuistAnalyticsBackboneBackend, TuistAnalyticsBackend, TuistAnalyticsCloudBackend, TuistAnalyticsDispatcher, URLSessionScheduler`

**Comment by adellibovi** [comment]
Will pick `CacheBundleBuilder`, `CacheFrameworkBuilder`, `CacheXCFrameworkBuilder` next

**Comment by danyf90** [comment]
I'll try to have a look at  XcodeBuildController, XcodeBuildControlling, Observable+XcodeBuildOutput

**Comment by adellibovi** [comment]
Closing this issue 🥳
